## THE NIGTHTINGALE PROJECT

In [4]:
import pandas as pd
import janitor
from lets_plot import *
LetsPlot.setup_html()

In [5]:
#Loading the 1854/1855 data
nightingale1 = pd.read_excel("raw_night_1854_1855.xlsx")

nightingale1.info()
nightingale1.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Month           12 non-null     object
 1   Avg Army Size   12 non-null     int64
 2   Disease Deaths  12 non-null     int64
 3   Wounds          12 non-null     int64
 4   Other Causes    12 non-null     int64
dtypes: int64(4), object(1)
memory usage: 612.0+ bytes

      Month  Avg Army Size  Disease Deaths  Wounds  Other Causes
0  Apr 1854           8571               1       0             5
1  May 1854          23333              12       0             9
2  Jun 1854          28333              11       0             6
3  Jul 1854          28722             359       0            23
4  Aug 1854          30246             828       1            30

In [6]:
#Seperating values in the column 'month'

(nightingale1.
 Month.str.split(" ", expand = True))


nightingale_1a = (nightingale1.Month.
    str.split(" ", expand = True).
    rename(columns = {0 : "month",
                     1 : "Year"}))

#Month and Year are both string data type after splitting
# we need to change year to integer

nightingale_1a["Year"] = nightingale_1a.Year.astype(int)

nightingale_1a.info()
    
nightingale_1a.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   month   12 non-null     object
 1   Year    12 non-null     int64
dtypes: int64(1), object(1)
memory usage: 324.0+ bytes

  month  Year
0   Apr  1854
1   May  1854
2   Jun  1854
3   Jul  1854
4   Aug  1854

In [7]:
#Joining the two 'nightingale1' and 'nightingale_1a'

nightingale_1b = pd.concat([nightingale_1a, nightingale1], axis = 1)

nightingale_1b.head()

  month  Year     Month  Avg Army Size  Disease Deaths  Wounds  Other Causes
0   Apr  1854  Apr 1854           8571               1       0             5
1   May  1854  May 1854          23333              12       0             9
2   Jun  1854  Jun 1854          28333              11       0             6
3   Jul  1854  Jul 1854          28722             359       0            23
4   Aug  1854  Aug 1854          30246             828       1            30

In [8]:
#filtering out the necessary column to shouw only cause of death per year and month

death_cause = nightingale_1b.loc[:, ["month", "Year", "Disease Deaths", "Wounds", "Other Causes"]]
death_cause.head()

  month  Year  Disease Deaths  Wounds  Other Causes
0   Apr  1854               1       0             5
1   May  1854              12       0             9
2   Jun  1854              11       0             6
3   Jul  1854             359       0            23
4   Aug  1854             828       1            30

In [9]:
death_cause_melted = death_cause.melt(
    id_vars=['month', 'Year'],
    value_vars=['Disease Deaths', 'Wounds', 'Other Causes'],
    var_name='Cause',
    value_name='Deaths'
)

death_cause_melted.head()

  month  Year           Cause  Deaths
0   Apr  1854  Disease Deaths       1
1   May  1854  Disease Deaths      12
2   Jun  1854  Disease Deaths      11
3   Jul  1854  Disease Deaths     359
4   Aug  1854  Disease Deaths     828

In [10]:
death_cause_melted.rename(columns = {"month": "Month"}, inplace=True)

death_cause_melted.head()

  Month  Year           Cause  Deaths
0   Apr  1854  Disease Deaths       1
1   May  1854  Disease Deaths      12
2   Jun  1854  Disease Deaths      11
3   Jul  1854  Disease Deaths     359
4   Aug  1854  Disease Deaths     828

In [24]:
death_cause_melted["Cause"] = death_cause_melted2["Cause"].replace("Disease Deaths", "Disease")

death_cause_melted

   Month  Year         Cause  Deaths
0    Apr  1854       Disease       1
1    May  1854       Disease      12
2    Jun  1854       Disease      11
3    Jul  1854       Disease     359
4    Aug  1854       Disease     828
5    Sep  1854       Disease     788
6    Oct  1854       Disease     503
7    Nov  1854       Disease     844
8    Dec  1854       Disease    1725
9    Jan  1855       Disease    2761
10   Feb  1855       Disease    2120
11   Mar  1855       Disease    1207
12   Apr  1854        Wounds       0
13   May  1854        Wounds       0
14   Jun  1854        Wounds       0
15   Jul  1854        Wounds       0
16   Aug  1854        Wounds       1
17   Sep  1854        Wounds      81
18   Oct  1854        Wounds     132
19   Nov  1854        Wounds     287
20   Dec  1854        Wounds     114
21   Jan  1855        Wounds      83
22   Feb  1855        Wounds      42
23   Mar  1855        Wounds      32
24   Apr  1854  Other Causes       5
25   May  1854  Other Causes       9
26   Jun  1854  Other Causes       6
27   Jul  1854  Other Causes      23
28   Aug  1854  Other Causes      30
29   Sep  1854  Other Causes      70
30   Oct  1854  Other Causes     128
31   Nov  1854  Other Causes     106
32   Dec  1854  Other Causes     131
33   Jan  1855  Other Causes     324
34   Feb  1855  Other Causes     361
35   Mar  1855  Other Causes     172

In [25]:
# Making a coxcomb chart

N1 = (
    ggplot(death_cause_melted, aes(x='Month', y='Deaths', fill='Cause'))
    + geom_bar(stat='identity', width=1)
    + coord_polar()
    +scale_color_manual(values = {"Disease Deaths" : "lightgrey",
                                    "Wounds" : "lightblue",
                                       "Other Causes" : "darkblue"})
    + theme_void()
    +labs(
        title= "APRIL 1854 TO MARCH 1855",
        X= "Month",
        y= "Number of death")
)

N1.show()

In [12]:
#Loading the 1855/1856 data
nightingale2 = pd.read_excel("raw_night_1855_1856.xlsx")

nightingale2.info()
nightingale2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Month           12 non-null     object
 1   Avg Army Size   12 non-null     int64
 2   Disease Deaths  12 non-null     int64
 3   Wounds          12 non-null     int64
 4   Other Causes    12 non-null     int64
dtypes: int64(4), object(1)
memory usage: 612.0+ bytes

      Month  Avg Army Size  Disease Deaths  Wounds  Other Causes
0  Apr 1855          32393             477      48            57
1  May 1855          35693             508      32            37
2  Jun 1855          40253             802      31            31
3  Jul 1855          35786             382      30            33
4  Aug 1855          51074             483      41            55

In [13]:
#Seperating values in the column 'month'

(nightingale2.
 Month.str.split(" ", expand = True))


nightingale_2a = (nightingale2.Month.
    str.split(" ", expand = True).
    rename(columns = {0 : "month",
                     1 : "Year"}))

#Month and Year are both string data type after splitting
# we need to change year to integer

nightingale_2a["Year"] = nightingale_2a.Year.astype(int)

nightingale_2a.info()
    
nightingale_2a.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   month   12 non-null     object
 1   Year    12 non-null     int64
dtypes: int64(1), object(1)
memory usage: 324.0+ bytes

  month  Year
0   Apr  1855
1   May  1855
2   Jun  1855
3   Jul  1855
4   Aug  1855

In [14]:
#Joining the two 'nightingale2' and 'nightingale_2a'

nightingale_2b = pd.concat([nightingale_2a, nightingale2], axis = 1)

nightingale_2b.head()

  month  Year     Month  Avg Army Size  Disease Deaths  Wounds  Other Causes
0   Apr  1855  Apr 1855          32393             477      48            57
1   May  1855  May 1855          35693             508      32            37
2   Jun  1855  Jun 1855          40253             802      31            31
3   Jul  1855  Jul 1855          35786             382      30            33
4   Aug  1855  Aug 1855          51074             483      41            55

In [15]:
#filtering out the necessary column to shouw only cause of death per year and month

death_cause2 = nightingale_2b.loc[:, ["month", "Year", "Disease Deaths", "Wounds", "Other Causes"]]
death_cause2.head()

  month  Year  Disease Deaths  Wounds  Other Causes
0   Apr  1855             477      48            57
1   May  1855             508      32            37
2   Jun  1855             802      31            31
3   Jul  1855             382      30            33
4   Aug  1855             483      41            55

In [16]:
#Making the table longer
death_cause_melted2 = death_cause2.melt(
    id_vars=['month', 'Year'],
    value_vars=['Disease Deaths', 'Wounds', 'Other Causes'],
    var_name='Cause',
    value_name='Deaths'
)

death_cause_melted2.head()

  month  Year           Cause  Deaths
0   Apr  1855  Disease Deaths     477
1   May  1855  Disease Deaths     508
2   Jun  1855  Disease Deaths     802
3   Jul  1855  Disease Deaths     382
4   Aug  1855  Disease Deaths     483

In [21]:
death_cause_melted2.rename(columns = {"month": "Month"}, inplace=True)

death_cause_melted2.head()

  Month  Year           Cause  Deaths
0   Apr  1855  Disease Deaths     477
1   May  1855  Disease Deaths     508
2   Jun  1855  Disease Deaths     802
3   Jul  1855  Disease Deaths     382
4   Aug  1855  Disease Deaths     483

In [23]:
death_cause_melted2["Cause"] = death_cause_melted2["Cause"].replace("Disease Deaths", "Disease")

death_cause_melted2

   Month  Year         Cause  Deaths
0    Apr  1855       Disease     477
1    May  1855       Disease     508
2    Jun  1855       Disease     802
3    Jul  1855       Disease     382
4    Aug  1855       Disease     483
5    Sep  1855       Disease     189
6    Oct  1855       Disease     128
7    Nov  1855       Disease     178
8    Dec  1855       Disease      91
9    Jan  1856       Disease      42
10   Feb  1856       Disease      24
11   Mar  1856       Disease      15
12   Apr  1855        Wounds      48
13   May  1855        Wounds      32
14   Jun  1855        Wounds      31
15   Jul  1855        Wounds      30
16   Aug  1855        Wounds      41
17   Sep  1855        Wounds      47
18   Oct  1855        Wounds      36
19   Nov  1855        Wounds      19
20   Dec  1855        Wounds      15
21   Jan  1856        Wounds       2
22   Feb  1856        Wounds       0
23   Mar  1856        Wounds       0
24   Apr  1855  Other Causes      57
25   May  1855  Other Causes      37
26   Jun  1855  Other Causes      31
27   Jul  1855  Other Causes      33
28   Aug  1855  Other Causes      55
29   Sep  1855  Other Causes      37
30   Oct  1855  Other Causes      33
31   Nov  1855  Other Causes      18
32   Dec  1855  Other Causes      15
33   Jan  1856  Other Causes       3
34   Feb  1856  Other Causes       2
35   Mar  1856  Other Causes       4

In [17]:
N2 = (
    ggplot(death_cause_melted2, aes(x='month', y='Deaths', fill='Cause'))
    + geom_bar(stat='identity', width=1)
    + coord_polar()
    +scale_color_manual(values = {"Disease Deaths" : "lightgrey",
                                    "Wounds" : "lightblue",
                                       "Other Causes" : "darkblue"})
    + theme_void()
    +labs(
        title= "APRIL 1855 TO MARCH 1856",
        X= "month",
        y= "Number of death")
)

N2.show()

In [18]:
from plotnine.composition import plot_spacer

combined = N1 | N2
combined

TypeError: unsupported operand type(s) for |: 'PlotSpec' and 'PlotSpec'

## EXPLANATION

str.split() = splits the value in the 'Month' column.

pd.concat() = it joined two tables 

df.melt() = Combines multiple columns into 1

var_name = 'cause' stores the name of the new column.'

value_name = stores values in the column